version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: db_mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27017:27017'

  back_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    environment:
      - MONGODB_URL=process.env.MONGODB_URL
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
