version: '3'
services:
  back_app:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - '8080:3000'
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - /usr/src/app/node_modules

  mongodb:
    image: mongo
    container_name: db_mongo
    volumes:
      - /mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata:
